"""Expand config/idea_bank with a wide multi-theme cold-storage card set."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "config" / "idea_bank"


def C(
    id: str,
    kind: str,
    title: str,
    text: str,
    keywords: list[str],
    tags: list[str] | None = None,
    examples: list[str] | None = None,
) -> dict:
    return {
        "id": id,
        "kind": kind,
        "title": title,
        "text": text,
        "keywords": keywords,
        "tags": tags or [],
        "examples": examples or [],
    }


def pack_fantasy() -> list[dict]:
    return [
        C("style.high_fantasy_courts", "style", "High court magic politics",
          "Shining capitals, formal magic schools, and court intrigue; power is public and dangerous to refuse.",
          ["high", "fantasy", "court", "magic", "noble", "kingdom"], ["fantasy"], ["ballroom treaty that is a trap"]),
        C("style.low_fantasy_mud", "style", "Low fantasy mud and knives",
          "Magic is rumor; problems are hunger, weather, and people with knives. Heroes look ordinary until cornered.",
          ["low", "fantasy", "gritty", "mud", "knife", "ordinary"], ["fantasy"], ["a broken cart axle starts the plot"]),
        C("style.sword_sorcery", "style", "Sword and sorcery road",
          "Wanderers, ruined idols, and short brutal victories; civilization is a tavern between wastelands.",
          ["sword", "sorcery", "barbarian", "ruin", "idol"], ["fantasy"], ["steal the idol, leave the town"]),
        C("style.fairy_border", "style", "Fair border bargain",
          "Paths that shift after dusk; bargains with the fair folk cost names, shadows, or first harvests.",
          ["fey", "fairy", "bargain", "border", "name", "shadow"], ["fantasy"], ["path home costs your nickname"]),
        C("style.dragon_marches", "style", "Dragon marches frontier",
          "Border keeps where dragons are weather systems; ash on the wind means taxes and funerals.",
          ["dragon", "march", "frontier", "ash", "keep"], ["fantasy"], ["ash rain cancels market day"]),
        C("style.dungeon_ecology", "style", "Living dungeon ecology",
          "Ruins that recycle explorers; fungus, traps, and territorial beasts form a working ecosystem.",
          ["dungeon", "ecology", "fungus", "trap", "ruin"], ["fantasy"], ["torch beetles farm dead adventurers"]),
        C("style.mythic_bronze", "style", "Bronze-age mythic",
          "Gods walk like weather; heroes are tools of curses and oaths more than free agents.",
          ["mythic", "bronze", "gods", "oath", "curse"], ["fantasy"], ["oath binds three generations"]),
        C("style.clockwork_fantasy", "style", "Clockwork fantasy city",
          "Gears under cobbles, guild patents on timepieces, and magic that smells of oil.",
          ["clockwork", "gear", "guild", "fantasy", "city"], ["fantasy"], ["stolen minute-spring"]),
        C("place.mage_academy", "place", "Glass-spired academy",
          "An academy of thin towers and stricter rivalries; exams can maim, tenure is politics.",
          ["academy", "mage", "school", "tower", "exam"], ["fantasy"], ["duel permitted in the east quad"]),
        C("place.elfwood_edge", "place", "Elfwood cutting edge",
          "Where logging roads meet older trees that remember debts; guides charge in secrets.",
          ["elf", "forest", "logging", "road", "secret"], ["fantasy"], ["guide fee: one true name"]),
        C("place.dwarf_hold", "place", "Underhold trade gate",
          "A stone gate city of ledgers and forge heat; clan seals open doors more than gold.",
          ["dwarf", "hold", "forge", "clan", "seal"], ["fantasy"], ["seal cracked means no passage"]),
        C("place.crossroad_inn", "place", "Crossroad inn of three banners",
          "An inn where three petty realms pretend neutrality; every table has a spy or a poet.",
          ["inn", "crossroad", "banner", "spy", "realm"], ["fantasy"], ["wrong toast starts a duel"]),
        C("place.oracle_cliff", "place", "Oracle cliff wind",
          "A cliff shrine where answers arrive as weather; pilgrims leave tools, not coins.",
          ["oracle", "cliff", "shrine", "pilgrim", "prophecy"], ["fantasy"], ["answer: fog until you repay"]),
        C("place.goblin_market", "place", "Midnight goblin market",
          "Stalls that sell impossible bargains; prices rearrange your memories.",
          ["goblin", "market", "bargain", "night", "fey"], ["fantasy"], ["buy back a childhood hour"]),
        C("place.wizard_tower_rent", "place", "Wizard tower rent flats",
          "A tower subdivided into cheap flats; residual spells leak through floorboards.",
          ["wizard", "tower", "rent", "flat", "spell"], ["fantasy"], ["neighbor summons at 3am"]),
        C("faction.mage_college", "faction", "College of Measured Flame",
          "A magic college that licenses fire and prosecutes unlicensed miracles.",
          ["college", "mage", "license", "fire", "law"], ["fantasy"], ["fine for unsanctioned light"]),
        C("faction.knight_order", "faction", "Order of the Quiet Shield",
          "Knights who protect roads more than thrones; oaths are short and public.",
          ["knight", "order", "road", "oath", "shield"], ["fantasy"], ["oath broken, shield returned"]),
        C("faction.thieves_guild", "faction", "Cistern thieves compact",
          "A guild under the sewers that sells silence and map scraps; dues are favors.",
          ["thieves", "guild", "sewer", "silence", "map"], ["fantasy"], ["dues: one useful rumor"]),
        C("faction.druid_circle", "faction", "Circle of Second Growth",
          "Druids who rewild roads slowly and fine loggers in curses measured by acres.",
          ["druid", "circle", "forest", "curse", "nature"], ["fantasy"], ["road sprouts overnight"]),
        C("ability.cantrip_ember", "ability", "Stubborn ember cantrip",
          "A tiny flame that refuses fancy shapes; useful for wet tinder, useless as a weapon until trained.",
          ["cantrip", "fire", "ember", "weak", "magic", "utility"], ["fantasy"], ["dry a sock, not a foe"]),
        C("ability.beast_whisper", "ability", "Half-trust beast hush",
          "Animals pause half a breath for your tone; they do not obey, only hesitate.",
          ["beast", "animal", "whisper", "nature", "weak"], ["fantasy"], ["wolf waits, then leaves"]),
        C("ability.ward_chalk", "ability", "Chalk ward line",
          "A chalk line that sometimes holds a lesser spirit; rain laughs at it.",
          ["ward", "chalk", "spirit", "ritual", "weak"], ["fantasy"], ["line holds until boots cross"]),
        C("ability.sword_memory", "ability", "Sword-form muscle echo",
          "Body remembers one incomplete drill from a dead teacher; form breaks under real fear until practiced.",
          ["sword", "form", "memory", "melee", "training"], ["fantasy"], ["third cut always late"]),
        C("ability.herb_sigil", "ability", "Herb-sigil mash",
          "Mash leaves into temporary marks that nudge luck or itch; strength scales with correct plant, not willpower.",
          ["herb", "sigil", "alchemy", "craft", "nature"], ["fantasy"], ["wrong leaf equals rash"]),
        C("ability.light_coin", "ability", "Coin-light flicker",
          "Make a coin glow faintly; drains nothing important until overused, then steals sleep.",
          ["light", "coin", "cantrip", "utility"], ["fantasy"], ["read a map under a table"]),
        C("tone.wondrous_cost", "tone", "Wonder with receipts",
          "Marvel is real and always billed later in debt, scars, or political obligation.",
          ["wonder", "cost", "magic", "edge", "fantasy"], ["fantasy"], ["miracle, invoice follows"]),
        C("tone.mythic_gravity", "tone", "Mythic gravity",
          "Language tilts epic without freeing the player from logistics and consequences.",
          ["mythic", "epic", "tone", "consequence"], ["fantasy"], ["oath echoes in weather"]),
        C("opening.caravan_hire", "opening", "Hired on at the caravan",
          "Start as cheap road labor; the first problem is a missing mule, not a dark lord.",
          ["caravan", "hire", "road", "opening", "travel"], ["fantasy"], ["mule tracks end at a shrine"]),
        C("opening.apprentice_letter", "opening", "Apprentice letter arrives late",
          "A delayed letter names you apprentice to someone already dead; tools still wait in a locked shed.",
          ["apprentice", "letter", "opening", "mentor"], ["fantasy"], ["shed lock is a riddle"]),
        C("opening.tour_gate", "opening", "Border gate stamp refused",
          "Customs refuses your stamp; the line behind you decides whether you are a problem or a story.",
          ["gate", "border", "stamp", "opening"], ["fantasy"], ["stamp ink is the wrong color"]),
    ]


def pack_dark() -> list[dict]:
    return [
        C("style.grimdark_mud", "style", "Grimdark mud calculus",
          "Every choice spends something permanent; hope is a budget line, not a theme song.",
          ["grimdark", "mud", "hopeless", "edge", "war"], ["grimdark"], ["victory costs a friend"]),
        C("style.gothic_ruin", "style", "Gothic rain-soaked ruin",
          "Cracked manors, family curses, and manners sharper than blades under constant rain.",
          ["gothic", "manor", "curse", "rain", "family"], ["horror"], ["portrait eyes track guests"]),
        C("style.cosmic_indifferent", "style", "Cosmic indifferent sky",
          "Stars that do not care; knowledge scrapes sanity; survival is small and temporary.",
          ["cosmic", "horror", "stars", "sanity", "indifferent"], ["horror"], ["constellation is a mouth"]),
        C("style.folk_horror", "style", "Folk harvest secrets",
          "Village smiles, harvest rites, and outsiders who leave wrong or stay wronger.",
          ["folk", "horror", "village", "harvest", "rite"], ["horror"], ["stranger at the bonfire"]),
        C("style.war_trench", "style", "Trench grit campaign",
          "Mud, ration rot, and officers who measure lives in meters of ground.",
          ["war", "trench", "military", "grit", "ration"], ["grimdark"], ["whistle means advance"]),
        C("style.body_horror_clinic", "style", "Body-clinic black market",
          "Medicine that rewrites flesh; clinics sell upgrades with side effects that have names.",
          ["body", "horror", "clinic", "flesh", "upgrade"], ["horror"], ["new hand remembers a crime"]),
        C("place.cursed_manor", "place", "Widowlight manor",
          "A manor where clocks disagree and servants polish silver that never stays clean.",
          ["manor", "cursed", "clock", "servant", "gothic"], ["horror"], ["dining room set for twelve ghosts"]),
        C("place.plague_quarter", "place", "Plague-barred quarter",
          "Gates painted with marks; healers bargain for gloves and names of the dead.",
          ["plague", "quarter", "gate", "healer", "disease"], ["grimdark"], ["mark means no exit"]),
        C("place.asylum_wing", "place", "Quiet wing of the asylum",
          "A wing where patients write true maps on walls; staff call it art.",
          ["asylum", "quiet", "map", "sanity", "horror"], ["horror"], ["map leads under the chapel"]),
        C("place.bone_cathedral", "place", "Bone-buttress cathedral",
          "A cathedral built of victory bones; sermons double as recruitment.",
          ["cathedral", "bone", "church", "war", "grim"], ["grimdark"], ["tithe is a finger bone"]),
        C("place.fog_fen", "place", "Fen of false lights",
          "Marsh lights that look like rescue; boats rot faster than maps update.",
          ["fen", "fog", "marsh", "light", "trap"], ["horror"], ["light answers to a name"]),
        C("place.trench_town", "place", "Trench-town of dugouts",
          "A town of dugouts and ration queues where the front is always one hill over.",
          ["trench", "town", "war", "ration"], ["grimdark"], ["queue fights over bread stamps"]),
        C("faction.inquisition", "faction", "Ash-seal inquisitors",
          "An order that burns heresy and sometimes the evidence of better futures.",
          ["inquisition", "ash", "heresy", "seal", "faith"], ["grimdark"], ["seal on your door overnight"]),
        C("faction.corpse_guild", "faction", "Corpse-cart guild",
          "They haul the dead and sell what the dead no longer need, quietly.",
          ["corpse", "guild", "cart", "dead", "grim"], ["grimdark"], ["ring returned for a fee"]),
        C("faction.cult_stars", "faction", "Circle of the Wrong Stars",
          "A cult that charts stars that should not rise; membership is a map you regret reading.",
          ["cult", "stars", "cosmic", "map", "ritual"], ["horror"], ["meeting under a black moon"]),
        C("faction.black_clinic", "faction", "Black clinic cooperative",
          "Surgeons without licenses who price mercy in organs and secrets.",
          ["clinic", "black", "surgeon", "organ"], ["horror"], ["payment plan in bloodwork"]),
        C("ability.scar_omen", "ability", "Scar-itch omen",
          "Old scars itch before betrayal or weather disaster; often wrong, sometimes life-saving.",
          ["scar", "omen", "sense", "weak", "survival"], ["horror"], ["itch before the knife"]),
        C("ability.cold_reading", "ability", "Funeral cold-reading",
          "Guess one true practical need of the recently dead from the room, not their secrets.",
          ["funeral", "dead", "insight", "weak", "social"], ["horror"], ["they needed the key, not revenge"]),
        C("ability.shadow_slip", "ability", "Shadow-slip half-step",
          "Step into a shadow for a blink; bright rooms and true names yank you back hard.",
          ["shadow", "stealth", "slip", "weak", "dark"], ["horror"], ["blink past a patrol"]),
        C("ability.blood_tally", "ability", "Blood-tally memory",
          "Remember who bled where in a room; starts as stains only you notice.",
          ["blood", "memory", "crime", "investigation"], ["grimdark"], ["stain under the rug pattern"]),
        C("ability.sanity_ledger", "ability", "Sanity ledger tick",
          "Track your own fraying as numbers only you see; useful until the numbers lie.",
          ["sanity", "ledger", "cosmic", "weak"], ["horror"], ["tick down after the chant"]),
        C("tone.bleak_fair", "tone", "Bleak but fair pressure",
          "The world is cruel without random spite; smart play still helps, soft hearts still bruise.",
          ["bleak", "fair", "edge", "grim", "dm"], ["grimdark"], ["good plan, costly success"]),
        C("tone.dread_slow", "tone", "Slow-building dread",
          "Fear accumulates in small wrong details; jumpscare is rare, unease is constant.",
          ["dread", "slow", "horror", "unease"], ["horror"], ["extra place setting again"]),
        C("death.scar_economy", "death", "Scar economy death rules",
          "Death is rare; maiming is common. Scars change rolls and social doors.",
          ["scar", "maim", "death", "injury", "edge"], ["grimdark"], ["lost eye means new viewpoint"]),
        C("opening.rain_funeral", "opening", "Rain-soaked funeral hire",
          "Hired as a spare pallbearer; the corpse is lighter than it should be.",
          ["funeral", "rain", "opening", "gothic"], ["horror"], ["coffin shifts mid-road"]),
        C("opening.deserter_papers", "opening", "Deserter papers in pocket",
          "Wake with another soldier's papers; the war thinks you are still owed to it.",
          ["deserter", "war", "papers", "opening"], ["grimdark"], ["checkpoint wants your name"]),
        C("opening.cult_invite", "opening", "Cult invite misdelivered",
          "An invite to a private sky-viewing arrives with your name almost right.",
          ["cult", "invite", "opening", "cosmic"], ["horror"], ["address is a rooftop"]),
    ]


def pack_scifi() -> list[dict]:
    return [
        C("style.cyber_neon", "style", "Neon alley cybergrind",
          "Megacity alleys, chrome debt, and corpo patents on your bloodstream.",
          ["cyberpunk", "neon", "corpo", "chrome", "hack"], ["scifi"], ["rent due in body-hours"]),
        C("style.space_salvage", "style", "Space salvage frontier",
          "Dead ships, thin air, and crews that share oxygen more carefully than secrets.",
          ["space", "salvage", "ship", "crew", "vacuum"], ["scifi"], ["airlock etiquette is law"]),
        C("style.system_apoc_ui", "style", "System-apocalypse UI weather",
          "After the break, menus overlay reality; quests are weather systems with body counts.",
          ["system", "apocalypse", "ui", "quest", "window"], ["system_rpg"], ["tutorial marker over a corpse"]),
        C("style.soft_solarpunk", "style", "Solarpunk repair commons",
          "Green roofs, shared tools, and conflicts about water rights rather than empire maps.",
          ["solarpunk", "green", "repair", "commons", "hope"], ["scifi"], ["who owns the spare pump"]),
        C("style.mecha_academy", "style", "Mecha hangar academy",
          "Cadets, frame calibrations, and exams that can crush steel and careers.",
          ["mecha", "academy", "hangar", "cadet", "frame"], ["scifi"], ["illegal night thruster test"]),
        C("style.colony_sim", "style", "Fragile colony sim",
          "A young colony where oxygen, food, and morale are the three real bosses.",
          ["colony", "oxygen", "food", "morale", "space"], ["scifi"], ["crop blight starts politics"]),
        C("style.time_loop_station", "style", "Station time-loop grind",
          "A looped day on a station; only skill growth and scars seem to stick.",
          ["time", "loop", "station", "grind", "system"], ["scifi"], ["same siren, new bruise"]),
        C("place.corpo_arcology", "place", "Arcology floor 214",
          "A vertical city block owned by one brand; elevators are class systems.",
          ["arcology", "corpo", "elevator", "class", "city"], ["scifi"], ["badge color is floor access"]),
        C("place.derelict_hull", "place", "Derelict hull market",
          "A market in a dead freighter; gravity is optional, honesty is expensive.",
          ["derelict", "hull", "market", "salvage", "zero-g"], ["scifi"], ["price list floats past"]),
        C("place.data_slum", "place", "Data-slum undergrid",
          "Cables for streets; people sell bandwidth and blood for uplink minutes.",
          ["data", "slum", "hack", "bandwidth", "grid"], ["scifi"], ["uplink cafe with teeth"]),
        C("place.orbital_station", "place", "Spoke-station customs",
          "A station where customs is a religion and contraband is a dialect.",
          ["orbital", "station", "customs", "contraband"], ["scifi"], ["undeclared seed pod"]),
        C("place.crashed_server", "place", "Crashed server-cathedral",
          "A building grown around a fallen mainframe; pilgrims ask questions that still compile.",
          ["server", "cathedral", "system", "ruin", "ai"], ["system_rpg"], ["error 77 is a prophecy"]),
        C("place.greenhouse_dome", "place", "Leaking greenhouse dome",
          "A dome farm where oxygen politics grow faster than vegetables.",
          ["greenhouse", "dome", "oxygen", "farm", "colony"], ["scifi"], ["valve locked by faction"]),
        C("faction.corpo_sec", "faction", "Brand security detail",
          "Corporate security that smiles with non-lethal policies and lethal exceptions.",
          ["corpo", "security", "brand", "police"], ["scifi"], ["smile protocol engaged"]),
        C("faction.runner_crew", "faction", "Alley runner crew",
          "A small netrunner crew that trades exploits like recipes and debts like currency.",
          ["runner", "hack", "crew", "net", "debt"], ["scifi"], ["exploit for a name erase"]),
        C("faction.salvage_union", "faction", "Vacuum salvage union",
          "Union rules on who may cut a hull; scabs float, sometimes literally.",
          ["salvage", "union", "space", "rules"], ["scifi"], ["cut order lottery"]),
        C("faction.window_priests", "faction", "Interface clergy",
          "People who interpret status windows as scripture and sell blessed UI skins.",
          ["window", "priest", "system", "ui", "cult"], ["system_rpg"], ["skin that lies about HP"]),
        C("ability.jack_static", "ability", "Jackport static sense",
          "Feel nearby active ports as scalp static; useful, noisy, and migraine-prone.",
          ["jack", "hack", "static", "cyber", "sense"], ["scifi"], ["static spikes at hidden camera"]),
        C("ability.suit_seal_habit", "ability", "Suit-seal double-check",
          "A near-useless habit of rechecking seals that compounds when vacuum is real risk.",
          ["suit", "seal", "space", "habit", "seed"], ["scifi"], ["catch a microtear early"]),
        C("ability.drone_nudge", "ability", "Drone nudge protocol",
          "Nudge a civilian drone one meter off course; military drones ignore you until upgraded.",
          ["drone", "nudge", "tech", "weak"], ["scifi"], ["shift a courier path"]),
        C("ability.menu_flicker", "ability", "Menu-edge flicker read",
          "See half a second of system menu chrome others miss; often garbage, rarely gold.",
          ["menu", "system", "ui", "read", "seed"], ["system_rpg"], ["glimpse cooldown true value"]),
        C("ability.scrap_solder", "ability", "Scrap-solder jury rig",
          "Solder dead boards into temporary life; smell of ozone means success or fire.",
          ["solder", "scrap", "repair", "craft", "tech"], ["scifi"], ["radio lives for three minutes"]),
        C("ability.adblock_blink", "ability", "Adblock blink filter",
          "Blink-filter one ad overlay; corporate AR fights back with brighter lies.",
          ["ad", "ar", "cyber", "filter", "weak"], ["scifi"], ["clear a door sign for a second"]),
        C("system.cold_questlog", "system", "Cold late quest log",
          "Objectives update late and omit the price; verify with sensors, not faith.",
          ["quest", "log", "system", "cold", "ui"], ["system_rpg"], ["complete, reward pending forever"]),
        C("system.diegetic_hud", "system", "Diegetic implant HUD",
          "HUD is an implant with ads, legal disclaimers, and optional lying overlays.",
          ["hud", "implant", "ads", "system"], ["scifi"], ["ad blocks your ammo count"]),
        C("system.skill_tree_scarce", "system", "Scarce skill-node tree",
          "Skill nodes are few and gated by materials, mentors, or crime, not free level spam.",
          ["skill", "tree", "node", "gate", "system"], ["system_rpg"], ["node needs rare coolant"]),
        C("tone.chrome_cynic", "tone", "Chrome cynicism",
          "Witty, tired, and allergic to corporate hope slogans; still capable of small loyalties.",
          ["cyberpunk", "cynic", "chrome", "tone"], ["scifi"], ["loyalty is a side quest"]),
        C("opening.first_window", "opening", "First window at dawn",
          "Sky cracks or network dies; a window appears over a practical crisis: water, air, rent.",
          ["window", "opening", "system", "crisis"], ["system_rpg"], ["quest: fix the filter"]),
        C("opening.pod_wakeup", "opening", "Cryo pod unpaid balance",
          "Wake from cryo with a debt invoice stuck to the glass and a station you do not recognize.",
          ["cryo", "pod", "debt", "opening", "space"], ["scifi"], ["invoice due before oxygen"]),
        C("opening.hangar_exam", "opening", "Hangar exam sabotage",
          "Your frame fails calibration mid-exam; the fault looks personal.",
          ["hangar", "exam", "mecha", "opening"], ["scifi"], ["sabotaged coupling"]),
    ]


def pack_historical() -> list[dict]:
    return [
        C("style.wuxia_face", "style", "Wuxia face and debt",
          "Sect politics, slow cultivation, and bows that can start wars; reputation outranks raw qi early on.",
          ["wuxia", "sect", "face", "cultivation", "debt"], ["wuxia"], ["wrong seat order is an insult"]),
        C("style.samurai_road", "style", "Samurai rain road",
          "Roads, inns, and honor tests under rain; swords matter, paperwork sometimes more.",
          ["samurai", "road", "honor", "japan", "rain"], ["historical"], ["pass requires a seal"]),
        C("style.pirate_tide", "style", "Pirate tide politics",
          "Ships, ports, and articles of agreement; mutiny is a vote with teeth.",
          ["pirate", "ship", "port", "mutiny", "sea"], ["historical"], ["articles rewritten at gunpoint"]),
        C("style.western_dust", "style", "Dust-town western",
          "Rail, claims, and sheriffs who are also creditors; noon is a calendar event.",
          ["western", "dust", "rail", "sheriff", "claim"], ["historical"], ["claim jumped overnight"]),
        C("style.regency_intrigue", "style", "Regency parlor knives",
          "Balls, letters, and fortunes; violence is social until it is not.",
          ["regency", "ball", "letter", "fortune", "intrigue"], ["historical"], ["dance card is a map"]),
        C("style.viking_saga", "style", "Saga-coast raids and law",
          "Longships, thrall politics, and assemblies where words can end bloodfeuds or start them.",
          ["viking", "saga", "ship", "law", "feud"], ["historical"], ["thing-meeting under rain"]),
        C("style.silk_road", "style", "Silk road caravan ledger",
          "Languages stack; water and trust are the real cargo between empires.",
          ["silk", "road", "caravan", "trade", "desert"], ["historical"], ["well guarded by three lies"]),
        C("style.noir_city", "style", "Raincoat city noir",
          "Cigarettes, case files, and bribes; truth is a commodity with markup.",
          ["noir", "detective", "city", "bribe", "case"], ["historical"], ["file missing page three"]),
        C("style.renaissance_inventor", "style", "Renaissance workshop wars",
          "Patrons, prototypes, and rival inventors who steal sketches and credit.",
          ["renaissance", "workshop", "inventor", "patron"], ["historical"], ["sketch stolen overnight"]),
        C("place.sect_outer_court", "place", "Outer court tea stones",
          "Stone tables for guests of unclear rank; tea temperature is a message.",
          ["sect", "court", "tea", "wuxia", "guest"], ["wuxia"], ["cold tea means cold welcome"]),
        C("place.port_free", "place", "Freeport of three flags",
          "A pirate-friendly port where flags change with the tide and laws rent by the hour.",
          ["port", "pirate", "flag", "law", "sea"], ["historical"], ["flag tax at noon"]),
        C("place.dust_saloon", "place", "Claim-jump saloon",
          "A saloon that doubles as claim office; piano covers arguments and gun checks.",
          ["saloon", "western", "claim", "piano"], ["historical"], ["piano stops means trouble"]),
        C("place.tea_house_spy", "place", "Tea house of paper walls",
          "Thin walls, thick politics; poets and killers share the same pot.",
          ["tea", "house", "spy", "wuxia", "poet"], ["wuxia"], ["poem contains a map"]),
        C("place.assembly_mound", "place", "Law-mound assembly",
          "An open mound where cases are shouted and blood-prices negotiated.",
          ["assembly", "law", "viking", "mound"], ["historical"], ["price of a hand announced"]),
        C("faction.customs_house", "faction", "Harbor customs ring",
          "Officials who tax honesty harder than smuggling when paid correctly.",
          ["customs", "harbor", "tax", "smuggle"], ["historical"], ["stamp costs a story"]),
        C("faction.ronin_band", "faction", "Ronin work band",
          "Masterless swords who sell protection by the week and principles by the day.",
          ["ronin", "band", "sword", "hire"], ["historical"], ["week contract, rainy clause"]),
        C("faction.cattle_barons", "faction", "Rail-and-cattle barons",
          "Land powers who fence water and buy sheriffs in bulk.",
          ["cattle", "rail", "baron", "western", "water"], ["historical"], ["fence moves at night"]),
        C("faction.patron_house", "faction", "Patron house of arts",
          "A noble house funding inventors and spies under the same roof.",
          ["patron", "noble", "inventor", "spy"], ["historical"], ["grant comes with a spy"]),
        C("ability.face_bow", "ability", "Protocol half-bow",
          "A bow that reads seating order; early mistakes teach faster than manuals.",
          ["bow", "face", "etiquette", "wuxia", "social"], ["wuxia"], ["bow depth is rank guess"]),
        C("ability.knot_sail", "ability", "Storm-sail knot memory",
          "Hands remember one storm knot under panic; calm seas make it clumsy.",
          ["knot", "sail", "storm", "pirate", "craft"], ["historical"], ["reef knot under green water"]),
        C("ability.track_dust", "ability", "Dust-track reading",
          "Read a day-old trail in dust; rain and herds erase your confidence.",
          ["track", "dust", "western", "survival"], ["historical"], ["shod horse, two riders"]),
        C("ability.letter_cipher", "ability", "Parlor letter cipher",
          "Spot one social cipher pattern in invitations; miss the second and you are the joke.",
          ["letter", "cipher", "regency", "social"], ["historical"], ["wax seal angle matters"]),
        C("ability.saga_recite", "ability", "Saga-line recall",
          "Recite one useful legal verse under pressure; wrong verse starts a feud.",
          ["saga", "law", "recite", "viking"], ["historical"], ["verse about guest-right"]),
        C("tone.formal_danger", "tone", "Formal danger manners",
          "Polite language carries threats; shouting is for people who already lost face.",
          ["formal", "manners", "danger", "wuxia", "tone"], ["wuxia"], ["apology is a weapon"]),
        C("tone.dusty_laconic", "tone", "Dusty laconic talk",
          "Few words, long silences, and violence that does not monologue.",
          ["laconic", "western", "dust", "tone"], ["historical"], ["nod means duel"]),
        C("opening.guest_disciple", "opening", "Accepted as outer disciple",
          "Enter a sect with a provisional token; one week to prove useful or leave poorer.",
          ["disciple", "sect", "opening", "wuxia"], ["wuxia"], ["token cracks if you lie"]),
        C("opening.pressed_crew", "opening", "Pressed into crew",
          "Wake on a ship with a new name chalked on a bunk and a debt to the captain.",
          ["pressed", "crew", "pirate", "opening", "ship"], ["historical"], ["bunk chalk is your name now"]),
        C("opening.train_ticket", "opening", "Train ticket to the wrong claim",
          "Ticket lands you in a dust town that expected a different specialist.",
          ["train", "ticket", "western", "opening"], ["historical"], ["porter calls wrong trade"]),
    ]


def pack_social() -> list[dict]:
    return [
        C("style.cozy_mystery", "style", "Cozy river mystery",
          "Small town secrets, soft danger, and justice that prefers truth over body counts.",
          ["cozy", "mystery", "village", "soft", "detective"], ["mystery"], ["pie contest hides a will"]),
        C("style.heist_crew", "style", "Heist crew clockwork",
          "Plans, roles, and timers; greed is a character, not just a motive.",
          ["heist", "crew", "plan", "timer", "crime"], ["heist"], ["two-minute window"]),
        C("style.political_intrigue", "style", "Council vote knives",
          "Every alliance is temporary; information is the sharpest inventory item.",
          ["politics", "vote", "alliance", "intrigue"], ["social"], ["vote bought with silence"]),
        C("style.slice_life_rpg", "style", "Slice-of-life stakes",
          "Jobs, festivals, and relationships drive progress; monsters are rare interruptions.",
          ["slice", "life", "festival", "job", "cozy"], ["slice"], ["festival planning is combat"]),
        C("style.investigation_noir", "style", "Casefile grind",
          "Clues, dead ends, and witnesses who edit themselves; progress is a board of strings.",
          ["investigation", "clue", "witness", "case"], ["mystery"], ["string connects three lies"]),
        C("style.school_arc", "style", "School arc pressures",
          "Classes, clubs, exams, and social ladders; the dungeon is the timetable.",
          ["school", "exam", "club", "arc", "social"], ["slice"], ["club room after hours"]),
        C("place.market_square", "place", "Market of seven smells",
          "A market where gossip travels faster than goods; every stall has a second ledger.",
          ["market", "gossip", "stall", "city"], ["social"], ["fishmonger knows the judge"]),
        C("place.opera_box", "place", "Opera box politics",
          "Private boxes where deals finish before the aria; ushers sell silence.",
          ["opera", "box", "deal", "elite"], ["social"], ["curtain call is an alibi"]),
        C("place.library_closed", "place", "After-hours library",
          "Stacks open to members with keys and blackmail; books leave footprints.",
          ["library", "book", "key", "secret"], ["mystery"], ["missing volume on curses"]),
        C("place.vault_street", "place", "Vault-row understreet",
          "A street of private vaults; locks are art, guards are critics.",
          ["vault", "heist", "lock", "guard"], ["heist"], ["shift change at 2:13"]),
        C("place.cafe_network", "place", "Cafe of quiet networks",
          "A cafe where tables are territories and overheard talk is inventory.",
          ["cafe", "network", "gossip", "social"], ["social"], ["table three is free if you tip secrets"]),
        C("faction.press_club", "faction", "Ink press club",
          "Writers who print truth for sale and fiction for free samples.",
          ["press", "ink", "news", "rumor"], ["social"], ["headline already written"]),
        C("faction.mask_society", "faction", "Midnight mask society",
          "A club where faces are optional and introductions are riddles.",
          ["mask", "society", "club", "riddle"], ["mystery"], ["mask color is faction"]),
        C("faction.crew_specialists", "faction", "Specialist heist table",
          "Specialists who hate each other professionally and need each other practically.",
          ["crew", "specialist", "heist", "table"], ["heist"], ["hacker hates the face"]),
        C("faction.parent_council", "faction", "Festival parent council",
          "A council that runs festivals and quietly runs the town.",
          ["festival", "council", "parent", "town"], ["slice"], ["budget is a battlefield"]),
        C("ability.lip_read", "ability", "Noisy-room lip skim",
          "Catch three words across a loud room; wrong lighting makes poetry of nonsense.",
          ["lip", "read", "social", "sense", "weak"], ["mystery"], ["catch the price, miss the name"]),
        C("ability.lock_ear", "ability", "Lock-click ear",
          "Hear pin stacks through thin doors; thick vaults hum lies.",
          ["lock", "ear", "heist", "craft"], ["heist"], ["false gate click"]),
        C("ability.alibi_clock", "ability", "Alibi clock sense",
          "Notice when a story timeline does not fit walking distances in this city.",
          ["alibi", "time", "investigation", "logic"], ["mystery"], ["ten minutes too short"]),
        C("ability.crowd_fade", "ability", "Crowd-fade posture",
          "Stand like furniture in a crowd; works until someone looks for you specifically.",
          ["crowd", "fade", "stealth", "social"], ["heist"], ["become a coat rack"]),
        C("ability.rumor_seed", "ability", "Rumor-seed plant",
          "Plant a short rumor that travels one social hop; farther hops mutate it.",
          ["rumor", "social", "seed", "talk"], ["social"], ["hop one is clean, hop three is wild"]),
        C("tone.wry_warm", "tone", "Wry warmth",
          "Humor that cares; danger exists but people still share bread and jokes.",
          ["warm", "wry", "cozy", "tone"], ["cozy"], ["joke mid-investigation"]),
        C("tone.tight_timer", "tone", "Tight timer tension",
          "Scenes feel like countdowns; waste is a villain.",
          ["timer", "tension", "heist", "tone"], ["heist"], ["ninety seconds of honesty"]),
        C("opening.wrong_invitation", "opening", "Wrong invitation in hand",
          "You arrive to a party you were not meant to attend; coat check knows your face anyway.",
          ["invitation", "party", "opening", "social"], ["mystery"], ["name card is almost yours"]),
        C("opening.job_briefing", "opening", "Job briefing on a napkin",
          "A heist briefing drawn on a napkin with coffee rings as walls.",
          ["job", "heist", "briefing", "opening"], ["heist"], ["napkin is the only map"]),
        C("opening.club_signup", "opening", "Club signup day chaos",
          "Signup tables, rival clubs, and a form that asks for skills you do not have yet.",
          ["club", "school", "signup", "opening"], ["slice"], ["form field: special talent"]),
    ]


def pack_travel() -> list[dict]:
    return [
        C("style.wilderness_trek", "style", "Wilderness long trek",
          "Distance, weather, and supply math; the map is optimistic.",
          ["wilderness", "trek", "weather", "supply", "travel"], ["travel"], ["river higher than the map"]),
        C("style.island_castaway", "style", "Island castaway craft",
          "Shore, wreckage, and social fracture among survivors.",
          ["island", "castaway", "wreck", "survival"], ["survival"], ["who keeps the flare"]),
        C("style.arctic_expedition", "style", "Arctic whiteout expedition",
          "Cold that edits plans; gear failure is a character.",
          ["arctic", "cold", "expedition", "gear"], ["survival"], ["stove dies at night"]),
        C("style.jungle_ruin", "style", "Jungle ruin crawl",
          "Green denser than walls; ruins breathe spores and old laws.",
          ["jungle", "ruin", "spore", "crawl"], ["travel"], ["path closes behind"]),
        C("style.desert_caravan", "style", "Desert well politics",
          "Wells own people; mirages are honest about being liars.",
          ["desert", "well", "caravan", "mirage"], ["travel"], ["well tax in water"]),
        C("style.sea_migration", "style", "Sea migration fleet",
          "Many small boats, shared charts, and storms that reassign leadership.",
          ["sea", "fleet", "migration", "storm"], ["travel"], ["chart burned for warmth"]),
        C("place.high_pass", "place", "High pass waystation",
          "A waystation where storms decide who stays and who freezes on the trail.",
          ["pass", "mountain", "waystation", "storm"], ["travel"], ["rope bridge half cut"]),
        C("place.reef_camp", "place", "Reef-camp on stilts",
          "Stilt huts over bright water; night brings different fish and different thieves.",
          ["reef", "camp", "stilt", "sea"], ["survival"], ["ladder pulled at dusk"]),
        C("place.glacier_lab", "place", "Glacier field lab",
          "A half-buried lab studying ice that moves like it thinks.",
          ["glacier", "lab", "ice", "science"], ["survival"], ["core sample screams slightly"]),
        C("place.oasis_market", "place", "Oasis market of clocks",
          "An oasis that sells time as much as water; clocks disagree on purpose.",
          ["oasis", "market", "water", "time", "desert"], ["travel"], ["hourglass tax"]),
        C("faction.ranger_corps", "faction", "Ranger corps of thin lines",
          "Rangers who mark safe paths and unmark unsafe people.",
          ["ranger", "path", "wilderness", "corps"], ["travel"], ["blaze mark means go around"]),
        C("faction.water_rights", "faction", "Water-rights compact",
          "Families who own minutes at the well and sell hours of peace.",
          ["water", "rights", "desert", "compact"], ["travel"], ["minute auction at dawn"]),
        C("faction.fleet_council", "faction", "Fleet council of captains",
          "Captains who vote with sails; minority boats get the worst charts.",
          ["fleet", "captain", "council", "sea"], ["travel"], ["vote for south, wind says no"]),
        C("ability.weather_knee", "ability", "Weather-knee ache",
          "An old ache predicts storms half the time; the other half it predicts regret.",
          ["weather", "knee", "sense", "survival", "weak"], ["survival"], ["ache before the whiteout"]),
        C("ability.forage_half", "ability", "Half-right forage",
          "Identify food that is probably safe; confidence is the real poison risk.",
          ["forage", "food", "survival", "nature"], ["survival"], ["berries: maybe"]),
        C("ability.rope_bridge", "ability", "Bridge-rope tension feel",
          "Feel when a rope bridge is one step from failure; starts as anxiety, becomes data.",
          ["rope", "bridge", "tension", "travel", "seed"], ["travel"], ["left cable sings wrong"]),
        C("ability.star_path", "ability", "Clouded star path",
          "Navigate by partial stars; overcast nights teach humility.",
          ["star", "navigate", "travel", "night"], ["travel"], ["two stars and a guess"]),
        C("ability.tide_clock", "ability", "Tide-clock gut",
          "Sense tide turns without a chart; lagoons still surprise you.",
          ["tide", "clock", "sea", "sense"], ["survival"], ["leave the sandbar now"]),
        C("tone.harsh_beauty", "tone", "Harsh beautiful land",
          "Landscapes awe and kill with the same honesty; people are smaller than weather.",
          ["harsh", "beauty", "nature", "tone"], ["travel"], ["sunrise after a bad night"]),
        C("opening.wreck_shore", "opening", "Wreck on an unnamed shore",
          "Surf, splinters, and a count of survivors that keeps changing.",
          ["wreck", "shore", "opening", "survival"], ["survival"], ["one more footprint than people"]),
        C("opening.map_with_gap", "opening", "Map with a deliberate gap",
          "A guide sells a map with a white patch labeled only as ask later.",
          ["map", "gap", "opening", "travel"], ["travel"], ["gap is a political border"]),
        C("opening.caravan_lottery", "opening", "Caravan seat lottery",
          "Seats assigned by lot; your seat-mate is a problem with a name.",
          ["caravan", "lottery", "opening", "travel"], ["travel"], ["seat-mate carries sealed jars"]),
    ]


def pack_systems_growth() -> list[dict]:
    return [
        C("ability.coin_flip_luck", "ability", "Weighted-coin almost-luck",
          "A coin habit that slightly biases trivial chance; never casinos, never life-or-death until ranked up.",
          ["luck", "coin", "chance", "weak", "seed"], ["general"], ["call the smaller risk"]),
        C("ability.voice_throw", "ability", "Soft voice throw",
          "Throw a whisper a few meters; crowded rooms garble it into comedy.",
          ["voice", "throw", "social", "trick"], ["social"], ["whisper from the wrong doorway"]),
        C("ability.pain_box", "ability", "Pain-box compartment",
          "Temporarily shelf pain into later; bill comes due with interest.",
          ["pain", "endurance", "cost", "body"], ["general"], ["run now, collapse later"]),
        C("ability.tool_echo", "ability", "Tool-echo improvisation",
          "Treat a wrong tool as almost-right for one task; breaks more often than it works early on.",
          ["tool", "improv", "craft", "jury"], ["craft"], ["screwdriver as pick"]),
        C("ability.face_blur", "ability", "Face-blur in memory",
          "People struggle to describe your face after brief meetings; cameras are less impressed.",
          ["face", "blur", "stealth", "social"], ["stealth"], ["sketch looks like anyone"]),
        C("ability.echo_location", "ability", "Click-echo room sense",
          "Click tongue to roughly map a dark room; noisy places defeat it.",
          ["echo", "dark", "sense", "perception"], ["dungeon"], ["pillar left, pit ahead-ish"]),
        C("ability.contract_clause", "ability", "Clause-catch reading",
          "Spot one predatory clause in a contract; legalese still swims.",
          ["contract", "clause", "law", "social"], ["social"], ["arbitration trap found"]),
        C("ability.seed_sprout", "ability", "Pocket seed sprout",
          "Force a seed to sprout early in poor soil; plant may hate you for it.",
          ["seed", "plant", "nature", "growth"], ["nature"], ["sprout in a crack"]),
        C("ability.spark_gap", "ability", "Spark-gap static jump",
          "Jump a tiny spark between metal points; useful for lights, bad for friends.",
          ["spark", "static", "tech", "weak"], ["scifi", "craft"], ["wake a dead bulb"]),
        C("ability.dream_tag", "ability", "Dream-tag recall",
          "Wake with one true tag from a dream about a real place; usually useless, rarely perfect.",
          ["dream", "recall", "omen", "weak"], ["mystery"], ["tag: blue door left"]),
        C("ability.pack_balance", "ability", "Pack-balance instinct",
          "Sense when a load will tip a cart or person; ignores emotional baggage.",
          ["pack", "balance", "travel", "utility"], ["travel"], ["shift weight starboard"]),
        C("ability.market_haggle", "ability", "Market half-haggle",
          "Shave a little price with patience; prideful sellers dig in harder.",
          ["haggle", "market", "social", "trade"], ["social"], ["two coins less"]),
        C("ability.poison_sip", "ability", "Poison-sip caution",
          "Detect harsh adulterants by micro-sip risk; still stupid without training.",
          ["poison", "sip", "caution", "survival"], ["survival"], ["bitter means stop"]),
        C("ability.mirror_copy", "ability", "Mirror-form copy",
          "Copy a simple physical motion after seeing it once; complex arts need ranks.",
          ["mirror", "copy", "learning", "training"], ["general"], ["copy the knot, fail the flourish"]),
        C("ability.quiet_door", "ability", "Quiet-door hinge feel",
          "Feel which doors squeak before opening; oil is still your friend.",
          ["door", "quiet", "stealth", "hinge"], ["stealth"], ["third hinge sings"]),
        C("ability.ink_smudge", "ability", "Ink-smudge forgery dab",
          "Smudge a seal almost convincingly; experts laugh until your rank rises.",
          ["ink", "forge", "seal", "crime", "weak"], ["heist"], ["almost the right crest"]),
        C("ability.pulse_count", "ability", "Pulse-count calm",
          "Count pulse to steady hands for one precise action; panic breaks the count.",
          ["pulse", "calm", "focus", "body"], ["general"], ["steady for the lockpick"]),
        C("growth.softcap_mentor", "growth", "Softcap until mentor",
          "Practice XP halves after mid-rank until a mentor, setback, or breakthrough event.",
          ["softcap", "mentor", "xp", "breakthrough", "rank"], ["math"], ["after C: half XP"]),
        C("growth.risk_tiers", "growth", "Three-tier risk XP",
          "Safe practice times one, contested times two, life-risk times three; life-risk failure can injure.",
          ["risk", "xp", "tier", "contested"], ["math"], ["contested duel drill"]),
        C("growth.reputation_xp", "growth", "Reputation-gated XP",
          "Some ranks need public proof or face, not just hours; shame blocks progress.",
          ["reputation", "face", "xp", "social", "rank"], ["math"], ["need a witnessed success"]),
        C("growth.material_sink", "growth", "Material sink ranks",
          "Rank-ups consume rare materials or cash; talent alone stalls.",
          ["material", "sink", "xp", "craft", "rank"], ["math"], ["need three rare coils"]),
        C("growth.seasonal_tick", "growth", "Seasonal slow tick",
          "Skills tick up slightly each season of relevant work; fast spikes need crisis.",
          ["season", "slow", "xp", "work"], ["math"], ["harvest season plus one tick"]),
        C("growth.fail_forward", "growth", "Fail-forward insight XP",
          "Meaningful failures grant more insight XP than easy wins; empty grind grants near nothing.",
          ["fail", "forward", "xp", "insight"], ["math"], ["botched lock teaches more"]),
        C("growth.pair_training", "growth", "Pair-training bonus",
          "Training with a rival or partner multiplies XP; alone practice is honest and slow.",
          ["pair", "rival", "train", "xp"], ["math"], ["spar with rival for double"]),
        C("skill.discovered_only", "skill", "Discover-on-use skills",
          "Skill names appear only after repeated use or teaching; no pre-bought trees at start.",
          ["discover", "skill", "use", "teach"], ["system"], ["name unlocks after third try"]),
        C("skill.mentor_gate", "skill", "Mentor-gated specialties",
          "Specialties require a person, manual, or institution, not pure self-study.",
          ["mentor", "specialty", "skill", "gate"], ["system"], ["no masterwork alone"]),
        C("skill.domain_only", "skill", "Single-domain focus",
          "One domain deep beats many shallow; second combat kit blocked at start.",
          ["domain", "focus", "one", "skill", "seed"], ["system"], ["rope deep, sword shallow ban"]),
        C("skill.social_ladder", "skill", "Social ladder ranks",
          "Etiquette and face ranks open quests more than stealth ranks in court-heavy worlds.",
          ["social", "ladder", "etiquette", "rank"], ["social"], ["rank B enters the inner hall"]),
        C("skill.craft_quality", "skill", "Craft quality steps",
          "Craft ranks convert to item quality steps with failure risk and material loss.",
          ["craft", "quality", "item", "rank"], ["craft"], ["B-rank blade vs D-rank nail"]),
        C("skill.system_node_cost", "skill", "System node real cost",
          "UI skill nodes cost stamina, money, or story flags, not free points only.",
          ["node", "system", "cost", "skill"], ["system_rpg"], ["node needs sleep debt"]),
        C("skill.language_ladder", "skill", "Language rank doors",
          "Language ranks open markets, courts, and secrets; wrong rank is comedy or insult.",
          ["language", "rank", "social", "travel"], ["social"], ["market slang is rank C"]),
        C("system.no_window", "system", "No window, only omens",
          "Progress is tracked by mentors, scars, and omens with no blue panes.",
          ["omen", "no", "window", "diegetic", "system"], ["fantasy"], ["mentor nod is rank tick"]),
        C("system.full_rpg_ui", "system", "Full RPG chrome UI",
          "Levels, inventories, and damage numbers are diegetic and contested by other systems.",
          ["rpg", "ui", "level", "inventory", "system"], ["system_rpg"], ["enemy hacks your HP display"]),
        C("system.profession_levels", "system", "Profession ladder only",
          "Levels are job ranks (dockhand to clerk), not murder XP.",
          ["profession", "job", "level", "ladder"], ["social"], ["promotion is a quest"]),
        C("system.honor_points", "system", "Honor point ledger",
          "A visible honor or face score that gates housing, weapons, and apologies.",
          ["honor", "face", "points", "system"], ["wuxia", "social"], ["apology restores two points"]),
        C("system.heat_meter", "system", "Heat meter crime",
          "Crime raises heat that changes patrols, prices, and who will talk to you.",
          ["heat", "crime", "meter", "system"], ["heist", "noir"], ["heat 3 closes the good fences"]),
    ]


def pack_meta() -> list[dict]:
    return [
        C("death.downed_not_deleted", "death", "Downed with scars",
          "Defeat drops you hard but not out of the story; recovery leaves marks that matter.",
          ["downed", "scar", "death", "recovery"], ["general"], ["wake in debt clinic"]),
        C("death.permadeath_rare", "death", "Rare true death",
          "True death is possible on brutal choices; most failures are costly survivals.",
          ["permadeath", "rare", "brutal", "death"], ["hard"], ["last stand is last"]),
        C("death.faction_ransom", "death", "Faction ransom death",
          "Death often becomes capture; factions buy, trade, or bury you for leverage.",
          ["ransom", "capture", "faction", "death"], ["social"], ["body sold to dock guild"]),
        C("death.honor_funeral", "death", "Honor funeral stakes",
          "How you die changes reputation tracks more than loot tables.",
          ["funeral", "honor", "death", "reputation"], ["wuxia", "historical"], ["bad death stains the sect"]),
        C("death.soft_reload_cost", "death", "Soft setback, hard cost",
          "Narrative setbacks replace delete; time, gear, and pride are the reload fee.",
          ["setback", "soft", "cost", "death"], ["cozy", "general"], ["week lost, gear pawned"]),
        C("loot.practical_scarce", "loot", "Practical scarce finds",
          "Boots, rope, permits, medicine; epic sparkles are rumors until late.",
          ["loot", "scarce", "practical", "gear"], ["hard"], ["dry socks as treasure"]),
        C("loot.information_loot", "loot", "Information as loot",
          "Maps, passwords, seals, and names beat gold in intrigue worlds.",
          ["info", "map", "password", "loot"], ["mystery", "social"], ["name worth a vault"]),
        C("loot.corpo_scrip", "loot", "Corpo scrip and licenses",
          "Company money and licenses beat cash; black market converts at cruel rates.",
          ["scrip", "license", "corpo", "loot"], ["scifi"], ["scrip only on brand floors"]),
        C("loot.sect_token", "loot", "Sect technique token",
          "Paper tokens that unlock training hours; forged tokens are death sentences.",
          ["token", "sect", "technique", "loot"], ["wuxia"], ["token for inner courtyard"]),
        C("loot.quest_material", "loot", "Quest-gated materials",
          "Upgrade materials drop from problems solved, not random sparkle piles.",
          ["material", "quest", "upgrade", "loot"], ["system_rpg"], ["coolant from fixed reactor"]),
        C("loot.cursed_useful", "loot", "Cursed but useful",
          "Best early gear has a social or physical tax; free power is bait.",
          ["cursed", "gear", "tax", "loot"], ["horror", "fantasy"], ["ring that records lies"]),
        C("loot.ration_chit", "loot", "Ration chit currency",
          "Food rights as money; forged chits start wars at the queue.",
          ["ration", "chit", "currency", "loot"], ["grimdark"], ["week of bread as bribe"]),
        C("npc.named_specialists", "npc", "Named specialists rare",
          "Most people are ordinary; specialists have names, rates, and schedules.",
          ["npc", "specialist", "named", "rare"], ["general"], ["one locksmith in town"]),
        C("npc.relative_power", "npc", "Relative power ladder",
          "NPC threat scales relative to player rank and local context, not global god stats.",
          ["npc", "scale", "rank", "relative"], ["general"], ["dock tough vs sect elder"]),
        C("npc.faction_faces", "npc", "Faction face characters",
          "Each faction has a public face, a quiet hand, and a disposable enforcer.",
          ["faction", "face", "npc", "enforcer"], ["social"], ["smile is the face, knife is the hand"]),
        C("npc.mentor_costly", "npc", "Mentors cost something",
          "Teachers want money, loyalty, risk, or humiliation, never free montages.",
          ["mentor", "cost", "npc", "train"], ["general"], ["teach fee: one dangerous favor"]),
        C("npc.rival_mirror", "npc", "Rival as mirror",
          "A rival shares your domain half a step ahead or behind; growth is comparative.",
          ["rival", "mirror", "npc", "growth"], ["general"], ["they learned the same seed"]),
        C("npc.crowd_pressure", "npc", "Crowd as pressure",
          "Crowds witness, record, and punish face loss; empty rooms are different games.",
          ["crowd", "witness", "face", "npc"], ["social"], ["market sees the slap"]),
        C("npc.child_witness", "npc", "Child witness complication",
          "A child saw too much; protecting them is a quest with social explosives.",
          ["child", "witness", "npc", "moral"], ["mystery"], ["they drew the killer wrong"]),
        C("opening.job_board", "opening", "Job board first coin",
          "Start at a board of bad jobs; the least bad one still has teeth.",
          ["job", "board", "opening", "coin"], ["general"], ["missing cat is not a cat"]),
        C("opening.debt_notice", "opening", "Debt notice on the door",
          "A notice names a sum and a deadline; story begins as accounting.",
          ["debt", "notice", "opening", "deadline"], ["grimdark", "social"], ["interest ticks daily"]),
        C("opening.wrong_body", "opening", "Wrong body, right skills",
          "Wake in a body with muscle memory that is not yours and papers that almost fit.",
          ["body", "transmigration", "opening", "identity"], ["isekai"], ["hands know a trade"]),
        C("opening.train_arrives", "opening", "Train arrives early",
          "A train dumps you in a town that expected someone else with your ticket.",
          ["train", "ticket", "opening", "town"], ["western", "noir"], ["porter calls the wrong name"]),
        C("opening.ritual_interrupts", "opening", "Ritual interrupted mid-chant",
          "You are the interruption; the circle still smokes and someone blames you.",
          ["ritual", "circle", "opening", "magic"], ["fantasy", "horror"], ["chalk smeared by your boot"]),
        C("opening.system_ping_job", "opening", "System pings a local job",
          "A window assigns a petty job with outsized consequences if ignored.",
          ["system", "ping", "job", "opening"], ["system_rpg"], ["ignore penalty: reputation bleed"]),
        C("style.isekai_fair_edge", "style", "Isekai fair edge",
          "Other world, no free OP, compounding seed skill, injuries and scarcity keep teeth.",
          ["isekai", "edge", "seed", "fair", "compound"], ["isekai"], ["window optional, scars not"]),
        C("style.urban_fantasy", "style", "Urban fantasy undercity",
          "Modern streets over older laws; magic hides in service corridors and late trains.",
          ["urban", "fantasy", "modern", "magic", "city"], ["fantasy"], ["subway that skips stations"]),
        C("style.superhero_street", "style", "Street-level cape work",
          "Powers exist but bills do too; cape work is a night job with PR problems.",
          ["superhero", "street", "cape", "power"], ["modern"], ["viral clip of your miss"]),
        C("style.post_magic_apoc", "style", "Post-magic wasteland",
          "Magic broke the world already; survivors treat spells like radiation.",
          ["post", "magic", "apoc", "wasteland"], ["fantasy", "apoc"], ["glow means leave"]),
        C("style.steampunk_fog", "style", "Steampunk fog empire",
          "Brass, smog, airships, and class war under clocktowers.",
          ["steampunk", "brass", "airship", "fog", "class"], ["historical", "fantasy"], ["smog tax riot"]),
        C("tone.hopeful_grit", "tone", "Hopeful grit",
          "Hard world, stubborn kindness; victories are small and kept.",
          ["hope", "grit", "kind", "tone"], ["general"], ["share water after the fight"]),
        C("tone.satirical_bite", "tone", "Satirical bite",
          "Systems and pomp get mocked; people still bleed when jokes land wrong.",
          ["satire", "bite", "tone", "system"], ["general"], ["quest log is a sitcom"]),
        C("tone.epic_distant", "tone", "Epic distant thunder",
          "Big history moves offscreen; your scenes stay local until you force scale.",
          ["epic", "distant", "local", "tone"], ["fantasy"], ["war is a rumor with smoke"]),
        C("tone.intimate_close", "tone", "Intimate close camera",
          "Focus on faces, hands, and small rooms; the world peeks in, does not swallow scenes.",
          ["intimate", "close", "tone", "character"], ["general"], ["argument over a shared bowl"]),
        C("style.harbor_noir_desk", "style", "Ration harbor after desk death",
          "Transmigration into dock labor and debt; former desk life is a liability, not a superpower.",
          ["harbor", "noir", "ration", "desk", "death", "transmigration"], ["grimdark"], ["keyboard hands, wrong knots"]),
        C("style.one_skill_isekai", "style", "One-skill compound isekai",
          "Exactly one weak seed domain compounds through risk and training; no free combat kit.",
          ["one", "skill", "seed", "compound", "isekai"], ["isekai"], ["domain later, never weather default"]),
    ]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "expand_fantasy.jsonl": pack_fantasy(),
        "expand_dark_horror.jsonl": pack_dark(),
        "expand_scifi_system.jsonl": pack_scifi(),
        "expand_historical.jsonl": pack_historical(),
        "expand_social_heist.jsonl": pack_social(),
        "expand_travel_survival.jsonl": pack_travel(),
        "expand_systems_growth.jsonl": pack_systems_growth(),
        "expand_meta_openings.jsonl": pack_meta(),
    }
    total = 0
    for name, cards in files.items():
        path = OUT / name
        with path.open("w", encoding="utf-8") as handle:
            for card in cards:
                handle.write(json.dumps(card, ensure_ascii=True) + "\n")
        total += len(cards)
        print(f"{name}: {len(cards)}")
    print(f"wrote {total} new cards to {OUT}")


if __name__ == "__main__":
    main()
